
-- CONSULTAS PARA BASE DE DCOMUENTACIÓN DE PROYECTOS PEOPLESOFT. 
-- RAUL BARRIOS 
-- 20180905

-- PARA BUSCAR LAS TABLAS DE DEFINCIÓN DE OBJETOS DE PEOPLE SOFT 
select * from DBA_TABLES WHERE TABLE_NAME LIKE '%CODE%' AND TABLE_NAME LIKE '%DEFN%' ORDER BY 2 ;
select * from DBA_TABLES WHERE TABLE_NAME LIKE '%CODE%' ORDER BY 2 ;



 SELECT  DECODE( A.OBJECTTYPE , 
 0,  'Record' , 
 1,  'Index',
 2,  'Field', 
 4,  'XLAT', 
 5,  'Pagina', 
 6,  'Menu', 
 7,  'Componente',  
 8 , 'People Code ',
 10, 'Query',
 19, 'Role',
 20, 'Process Definition',
 21, 'Process Server Definition',
 22, 'Process Type Definition',
 23, 'Process Job Definition',
 23, 'JOB Definition',
 25, 'Message Catalog',
 30, 'SQL', 
 33, 'Application Engine ' ,
 32, 'Conponent Interface ' ,
 37, 'Message Web Service',
 34 ,'Application Engine Section',
 43 ,'Application Engine Step',
 44, 'PeopleCodePage ', 
 46, 'People code Component',
 48, 'PeoplecodeComponent ', 
 53, 'Lista de permisos',  
 54, 'Regsitro ' , 
 55 ,'Estructura',
 56 ,'url',
 57, 'Application Package',
 58, 'Application Package Class',
 79, 'Web service ',
 80, 'Operation',
 81, 'Service Operation Handler',
 82, 'Service Operation Version',
 83, 'Service Operation Routing',
 85, 'BIP Template Definition',
 86, 'BIP Report defintion',
 87, 'BIP File definition',
 89, 'WSDL',
 90, 'Message Schema') TIPO, 
 A.OBJECTVALUE1 ||' '|| A.OBJECTVALUE2 ||' '||  A.OBJECTVALUE3 ||' ' ||A.OBJECTVALUE4 DESCRIPCION 
 FROM PSPROJECTITEM A 
 WHERE PROJECTNAME = 'CK_CS_4499FACELE_GRAL'
   ORDER BY 1,2;
   
--   select *  FROM PSPROJECTITEM A WHERE PROJECTNAME = 'CK_CS_4499FACELE_GRAL';
--   select count(1), A.OBJECTTYPE  FROM PSPROJECTITEM A WHERE PROJECTNAME = 'CK_CS_4499FACELE_GRAL' group by A.OBJECTTYPE order by count(1);
 
-- record del proyecto.
 SELECT  DISTINCT b.RECNAME,  DECODE( RECTYPE , 
 0,  'Data Table' ,  1,  'Vista', 2,  'Derived Work', 3,  'Subrecord', 4,  'Huy!', 5,  'Vista Dinámica', 6,  'Query view', 7,  'Tabla Temporal' ) tipo, RECTYPE,
 NVL(TRIM(b.RECDESCR),C.RECDESCR) DESCR
 FROM PSPROJECTITEM A, PSRECDEFN B , PSRECDEFNLANG C 
 WHERE PROJECTNAME='CK_CS_4499FACELE_GRAL' 
 AND A.OBJECTVALUE1 = b.recname(+)
 AND A.OBJECTVALUE1 = c.recname(+) ;
 
 -- Estructura de records del proyecto 
 --  APP ENG del proyecto.
 
 SELECT DISTINCT A.OBJECTVALUE1,c.descr FROM PSPROJECTITEM A,PSAEAPPLLANG C WHERE PROJECTNAME='CK_CS_4499FACELE_GRAL' AND A.OBJECTVALUE1 = C.AE_APPLID(+) AND A.OBJECTTYPE = 33;
 --  APP PACK del proyecto.
 SELECT DISTINCT A.OBJECTVALUE1,c.descr FROM PSPROJECTITEM A,PSPACKAGELANG C WHERE PROJECTNAME='CK_CS_4499FACELE_GRAL' AND A.OBJECTVALUE1 = C.packageroot(+) AND A.OBJECTTYPE = 57 AND packageroot = packageid;
 --  Defición de reportes del proyecto.
SELECT DISTINCT A.OBJECTVALUE1,c.descr FROM PSPROJECTITEM A,PSXPRPTDEFN C WHERE PROJECTNAME='CK_CS_4499FACELE_GRAL' AND A.OBJECTVALUE1 = C.REPORT_DEFN_ID(+) AND A.OBJECTTYPE = 86;
-- DEFINICION DE PLANTILLAS 
SELECT DISTINCT A.OBJECTVALUE1,c.descr FROM PSPROJECTITEM A,PSXPTMPLDEFN C WHERE PROJECTNAME='CK_CS_4499FACELE_GRAL' AND A.OBJECTVALUE1 = C.TMPLDEFN_ID(+) AND A.OBJECTTYPE = 85;
-- definicion de componentes 
SELECT DISTINCT A.OBJECTVALUE1,c.descr FROM PSPROJECTITEM A,PSPNLGDEFNLANG C WHERE PROJECTNAME='CK_CS_4499FACELE_GRAL' AND A.OBJECTVALUE1 = C.PNLGRPNAME(+) AND A.OBJECTTYPE = 7 ORDER BY 1 ;
-- CAMPOS 
SELECT DISTINCT A.OBJECTVALUE1, DECODE ( C.FIELDTYPE,0 , 'C',1 , 'T',2 , 'N',3 , 'N',4 , 'D',5 , 'T',6 , 'DT',8 , 'I' ) TIPO, C.LENGTH , L.LONGNAME, L.SHORTNAME
FROM PSPROJECTITEM A, PSDBFIELD C, PSDBFLDLABL L WHERE PROJECTNAME  = 'CK_CS_4499FACELE_GRAL' AND A.OBJECTVALUE1 = C.FIELDNAME(+)  AND A.OBJECTVALUE1 = L.FIELDNAME(+)  
AND A.OBJECTTYPE   = 2 ORDER BY 1 ;
-- campos sencillos 
SELECT DISTINCT A.OBJECTVALUE1 , L.LONGNAME FROM PSPROJECTITEM A, PSDBFLDLABL L WHERE PROJECTNAME  = 'CK_CS_4499FACELE_GRAL' AND A.OBJECTVALUE1 = L.FIELDNAME(+) AND A.OBJECTTYPE   = 2 ORDER BY 1 ;
-- MENU  
SELECT DISTINCT A.OBJECTVALUE1, B.descr FROM PSPROJECTITEM A, PSMENUDEFNLANG B WHERE PROJECTNAME  = 'CK_CS_4499FACELE_GRAL' AND A.OBJECTVALUE1 = B.MENUNAME(+) AND A.OBJECTTYPE = 6 ORDER BY 1;
-- MENSAJES WEB  
SELECT DISTINCT A.OBJECTVALUE1, B.descr FROM PSPROJECTITEM A, PSMSGDEFN B WHERE PROJECTNAME  = 'CK_CS_4499FACELE_GRAL' AND A.OBJECTVALUE1 = B.MSGNAME(+) AND A.OBJECTTYPE = 37 ORDER BY 1;
-- PAGINAS
SELECT DISTINCT A.OBJECTVALUE1, B.descr FROM PSPROJECTITEM A,  PSPNLDEFNLANG B WHERE PROJECTNAME  = 'CK_CS_4499FACELE_GRAL' AND A.OBJECTVALUE1 = B.PNLNAME(+) AND A.OBJECTTYPE = 5 ORDER BY 1;
-- RECORD
-- campos de records del proyecto 
select  distinct a.OBJECTVALUE1, NVL(B.RECDESCR,C.RECDESCR) DESCR FROM PSPROJECTITEM a ,PSRECDEFN B, PSRECDEFNLANG C
WHERE PROJECTNAME  = 'CK_CS_4499FACELE_GRAL' AND A.OBJECTVALUE1 = B.RECNAME(+) AND A.OBJECTVALUE1 = C.RECNAME(+) AND A.OBJECTTYPE = 0 ORDER BY 1;
-- QUERY 
select  distinct a.OBJECTVALUE1, NVL(B.DESCR,C.DESCR) DESCR FROM PSPROJECTITEM a , PSQRYDEFN B, PSQRYDEFNLANG C 
WHERE PROJECTNAME  = 'CK_CS_4499FACELE_GRAL' AND A.OBJECTVALUE1 = B.QRYNAME(+) AND A.OBJECTVALUE1 = C.QRYNAME(+) 
AND A.OBJECTTYPE = 10 ORDER BY 1;
-- SQL
select  distinct a.OBJECTVALUE1, NVL(B.DESCR,C.DESCR) DESCR FROM PSPROJECTITEM a , PSSQLDEFN B 
WHERE PROJECTNAME  = 'CK_CS_4499FACELE_GRAL' AND A.OBJECTVALUE1 = B.SQLID(+) 
AND A.OBJECTTYPE = 30 ORDER BY 1;
-- URL
select  distinct a.OBJECTVALUE1, B.DESCR DESCR FROM PSPROJECTITEM a , PSURLDEFN B 
WHERE PROJECTNAME  = 'CK_CS_4499FACELE_GRAL' AND A.OBJECTVALUE1 = B.URL_ID(+) 
AND A.OBJECTTYPE = 56 ORDER BY 1;
-- web services 
select  distinct a.OBJECTVALUE1, B.DESCR DESCR FROM PSPROJECTITEM a , PSSERVICE B 
WHERE PROJECTNAME  = 'CK_CS_4499FACELE_GRAL' AND A.OBJECTVALUE1 = B.IB_SERVICENAME(+) 
AND A.OBJECTTYPE = 79 ORDER BY 1;}
-- xlat
select  distinct a.OBJECTVALUE1, A.OBJECTVALUE2, B.EFF_STATUS, B.EFFDT, XLATLONGNAME, XLATSHORTNAME 
FROM PSPROJECTITEM a , PSXLATITEM B 
WHERE PROJECTNAME  = 'CK_CS_4499FACELE_GRAL' 
AND A.OBJECTVALUE1 = B.FIELDNAME(+) 
AND A.OBJECTVALUE2 = B.FIELDVALUE(+) 
AND A.OBJECTTYPE = 4
ORDER BY 1;





-- campos de records del proyecto 
select  distinct R.recname,c.FIELDNAME, 
DECODE (C.FIELDTYPE,0 , 'C',1 , 'T',2 , 'N',3 , 'N',4 , 'D',5 , 'T',6 , 'DT',8 , 'I') TIPO,  
C.LENGTH , DECODE(K.INDEXID,'_','SI') KEY ,' ' , R.EDITTABLE , L.LONGNAME, L.SHORTNAME
FROM PSPROJECTITEM P ,
 PSRECFIELD R ,
 PSDBFIELD C ,
 PSKEYDEFN K ,
 PSDBFLDLABL L , 
 PSDBFLDLABLLANG LE
WHERE P.PROJECTNAME='CK_CS_4499FACELE_GRAL' AND P.OBJECTTYPE = 0  
AND P.OBJECTVALUE1 = R.RECNAME 
AND R.FIELDNAME = C.FIELDNAME 
AND R.FIELDNAME = L.FIELDNAME 
AND R.FIELDNAME = L.LABEL_ID 
AND L.LABEL_ID = LE.LABEL_ID
and LE.LANGUAGE_CD = 'ESP' 
AND R.RECNAME = k.RECNAME (+)
AND R.FIELDNAME = k.FIELDNAME (+)
ORDER BY R.recname, c.fieldname;