SELECT N01.PORTAL_URI_SEG2 AS component ,
  N09.PORTAL_LABEL  || '>'  ||
  N08.PORTAL_LABEL  || '>'  ||
  N07.PORTAL_LABEL  || '>'  ||
  N06.PORTAL_LABEL  || '>'  || 
  N05.PORTAL_LABEL  || '>'  ||
  N04.PORTAL_LABEL  || '>'  ||
  N03.PORTAL_LABEL  || '>'  ||
  N02.PORTAL_LABEL  || '>'  ||
  N01.PORTAL_LABEL AS Menu_Path ,
  N01.PORTAL_URLTEXT ,
  N01.PORTAL_ISPUBLIC AS Active
 -- N01.LASTUPDOPRID ,
 -- N01.LASTUPDDTTM
FROM 
	PSPRSMDEFN N01,
	PSPRSMDEFN N02,
	PSPRSMDEFN N03,
	PSPRSMDEFN N04,
	PSPRSMDEFN N05,
	PSPRSMDEFN N06,
	PSPRSMDEFN N07,
	PSPRSMDEFN N08,
	PSPRSMDEFN N09
WHERE N01.PORTAL_URI_SEG2 LIKE '%CK_PARAMACCTPYG_CMP%' -- Component Name
AND N01.PORTAL_PRNTOBJNAME = N02.PORTAL_OBJNAME(+)
AND N02.PORTAL_PRNTOBJNAME = N03.PORTAL_OBJNAME(+)
AND N03.PORTAL_PRNTOBJNAME = N04.PORTAL_OBJNAME(+)
AND N04.PORTAL_PRNTOBJNAME = N05.PORTAL_OBJNAME(+)
AND N05.PORTAL_PRNTOBJNAME = N06.PORTAL_OBJNAME(+)
AND N06.PORTAL_PRNTOBJNAME = N07.PORTAL_OBJNAME(+)
AND N07.PORTAL_PRNTOBJNAME = N08.PORTAL_OBJNAME(+)
AND N08.PORTAL_PRNTOBJNAME = N09.PORTAL_OBJNAME(+)
AND (N01.PORTAL_NAME       = 'EMPLOYEE' OR N01.PORTAL_NAME IS NULL )
AND (N02.PORTAL_NAME       = 'EMPLOYEE' OR N02.PORTAL_NAME IS NULL )
AND (N03.PORTAL_NAME       = 'EMPLOYEE' OR N03.PORTAL_NAME IS NULL )
AND (N04.PORTAL_NAME       = 'EMPLOYEE' OR N04.PORTAL_NAME IS NULL )
AND (N05.PORTAL_NAME       = 'EMPLOYEE' OR N05.PORTAL_NAME IS NULL ) 
AND (N06.PORTAL_NAME       = 'EMPLOYEE' OR N06.PORTAL_NAME IS NULL )
AND (N07.PORTAL_NAME       = 'EMPLOYEE' OR N07.PORTAL_NAME IS NULL )
AND (N08.PORTAL_NAME       = 'EMPLOYEE' OR N08.PORTAL_NAME IS NULL )
AND (N09.PORTAL_NAME       = 'EMPLOYEE' OR N09.PORTAL_NAME IS NULL ) 
ORDER BY N01.PORTAL_URI_SEG2;