SELECT (CASE OBJECTTYPE WHEN 0 THEN CASE NVL((SELECT RECTYPE FROM PSRECDEFN WHERE RECNAME = OBJECTVALUE1), 99)
 WHEN 0 THEN 'SQL Table in DB'
 WHEN 1 THEN 'SQL View in DB'
 WHEN 2 THEN 'Work Record'
 WHEN 3 THEN 'Sub Record'
 WHEN 5 THEN 'Dynamic View'
 WHEN 6 THEN 'Query View'
 WHEN 7 THEN 'Temporary Table'
 ELSE 'Other Record or Deleted' END
WHEN 1 THEN 'Index'
WHEN 2 THEN 'Field'
WHEN 3 THEN 'Field Format'
WHEN 4 THEN 'Translate Value'
WHEN 5 THEN 'Pages'
WHEN 6 THEN 'Menus'
WHEN 7 THEN 'Components'
WHEN 8 THEN 'Record PeopleCode'
WHEN 9 THEN 'Menu PeopleCode'
WHEN 10 THEN 'Query'
WHEN 11 THEN 'Tree Structures'
WHEN 12 THEN 'Trees'
WHEN 13 THEN 'Access group'
WHEN 14 THEN 'Color'
WHEN 15 THEN 'Style'
WHEN 16 THEN 'N/A'
WHEN 17 THEN 'Business process'
WHEN 18 THEN 'Activity'
WHEN 19 THEN 'Role'
WHEN 20 THEN 'Process Definition'
WHEN 21 THEN 'Server Definition'
WHEN 22 THEN 'Process Type Definition'
WHEN 23 THEN 'Job Definitions'
WHEN 24 THEN 'Recurrence Definition'
WHEN 25 THEN 'Message Catalog'
WHEN 26 THEN 'Dimension'
WHEN 27 THEN 'Cube Definitions'
WHEN 28 THEN 'Cube Instance Definitions'
WHEN 29 THEN 'Business Interlink'
WHEN 30 THEN CASE OBJECTVALUE2
 WHEN '0' THEN 'SQL Object'
 WHEN '1' THEN 'App Engine SQL'
 WHEN '2' THEN 'Record View SQL'
 WHEN '5' THEN 'Query for DDAUDIT or SYSAUDIT'
 WHEN '6' THEN 'App Engine XML SQL'
 ELSE 'SQL' END
WHEN 31 THEN 'File Layout Definition'
WHEN 32 THEN 'Component Interfaces'
WHEN 33 THEN 'AE program'
WHEN 34 THEN 'AE section'
WHEN 35 THEN 'Message Node'
WHEN 36 THEN 'Message Channel'
WHEN 37 THEN 'Message'
WHEN 38 THEN 'Approval rule set'
WHEN 39 THEN 'Message PeopleCode'
WHEN 40 THEN 'Subscription PeopleCode'
WHEN 41 THEN 'N/A'
WHEN 42 THEN 'Component Interface PeopleCode'
WHEN 43 THEN 'AE PeopleCode'
WHEN 44 THEN 'Page PeopleCode'
WHEN 45 THEN 'Page Field PeopleCode'
WHEN 46 THEN 'Component PeopleCode'
WHEN 47 THEN 'Component Record PeopleCode'
WHEN 48 THEN 'Component Rec Fld PeopleCode'
WHEN 49 THEN 'Image'
WHEN 50 THEN 'Style sheet'
WHEN 51 THEN 'HTML'
WHEN 52 THEN 'Not used'
WHEN 53 THEN 'Permission List'
WHEN 54 THEN 'Portal Registry Definitions'
WHEN 55 THEN 'Portal Registry Structures'
WHEN 56 THEN 'URL Definitions'
WHEN 57 THEN 'Application Packages'
WHEN 58 THEN 'Application Package Peoplecode'
WHEN 59 THEN 'Portal Registry User Homepage'
WHEN 60 THEN 'Problem Type'
WHEN 61 THEN 'Archive Templates'
WHEN 62 THEN 'XSLT'
WHEN 63 THEN 'Portal Registry User Favorite'
WHEN 64 THEN 'Mobile Page'
WHEN 65 THEN 'Relationships'
WHEN 66 THEN 'Component Interface Property Peoplecode'
WHEN 67 THEN 'Optimization Models'
WHEN 68 THEN 'File References'
WHEN 69 THEN 'File Type Codes'
WHEN 70 THEN 'Archive Object Definitions'
WHEN 71 THEN 'Archive Templates (Type 2)'
WHEN 72 THEN 'Diagnostic Plug In'
WHEN 73 THEN 'Analytic Model'
WHEN 79 THEN 'Service Definition'
WHEN 80 THEN 'Service Operation'
WHEN 83 THEN 'Service Route Definition'
WHEN 87 THEN 'XMLP File Defn'
WHEN 85 THEN 'XMLP Template Defn'
WHEN 86 THEN 'XMLP Report Defn'
WHEN 88 THEN 'XMLP Data Src Defn'

ELSE 'UNKNOWN OBJECT TYPE' END) AS OBJECTTYPE
, OBJECTVALUE1
, OBJECTVALUE2
, OBJECTVALUE3
, OBJECTVALUE4
-- , NVL((SELECT SQLTEXT FROM PSSQLTEXTDEFN WHERE SQLID = OBJECTVALUE1), 'N/A') AS SQLTEXT
FROM PSPROJECTITEM
 WHERE PROJECTNAME = 'CK_CS_4499FACELE_GRAL' --- Replace w/ your project name
 ORDER BY OBJECTTYPE, OBJECTVALUE1, OBJECTVALUE2, OBJECTVALUE3;
