-- BORRAR TABLAS DE MENSAJES WEBSERVICE POR OPERACION
DELETE FROM PSIBLOGHDR  WHERE GUID IN (SELECT GUID FROM PSIBLOGHDR WHERE IB_OPERATIONNAME = 'SINCRONIZARORDENESCOMPRA');
DELETE FROM PSIBLOGDATA WHERE GUID IN (SELECT GUID FROM PSIBLOGHDR WHERE IB_OPERATIONNAME = 'SINCRONIZARORDENESCOMPRA');
DELETE FROM PSIBLOGERR  WHERE GUID IN (SELECT GUID FROM PSIBLOGHDR WHERE IB_OPERATIONNAME = 'SINCRONIZARORDENESCOMPRA');
DELETE FROM PSIBLOGERRP WHERE GUID IN (SELECT GUID FROM PSIBLOGHDR WHERE IB_OPERATIONNAME = 'SINCRONIZARORDENESCOMPRA');
DELETE FROM PSIBLOGIBINFO WHERE GUID IN (SELECT GUID FROM PSIBLOGHDR WHERE IB_OPERATIONNAME = 'SINCRONIZARORDENESCOMPRA');
COMMIT;